export const ACTION_GET_LIST_USERS = 'ACTION_GET_LIST_USERS';
export const ACTION_GET_DEFAULT_INFO = 'ACTION_GET_DEFAULT_INFO';
export const ACTION_UPDATE_USER = 'ACTION_UPDATE_USER';
export const ACTION_ADD_USER = 'ACTION_ADD_USER';
export const ACTION_DELETE_USER = 'ACTION_DELETE_USER';